Feature: ["feature/*", "feat/*", "*feature/*", "*feat/*"]
Fix: ["fix/*", "*fix/*", "*bugfix/*"]
Chore: ["chore/*", "*chore/*"]
Test: ["test/*", "*test/*"]
Docs: ["docs/*", "*docs/*"]
Refactor: ["refactor/*", "refact/*", "*refactor/*", "*refact/*"]
Style: ["style/*", "*style/*"]
CI: ["ci/*", "*ci/*"]
Performance: ["perf/*", "*perf/*", "performance/*", "*performance/*"]
Fixed-branch: ["fixed-branch-name", "*fixed-branch-name"]
"Developer Experience (DX)": ["dx/*"]
