feature: ["feature/*", "feat/*", "*feature/*", "*feat/*"]
fix: ["fix/*", "*fix/*", "*bugfix/*"]
chore: ["chore/*", "*chore/*"]
test: ["test/*", "*test/*"]
docs: ["docs/*", "*docs/*"]
refactor: ["refactor/*", "refact/*", "*refactor/*", "*refact/*"]
style: ["style/*", "*style/*"]
ci: ["ci/*", "*ci/*"]
perf: ["perf/*", "*perf/*"]
fixed-branch: ["fixed-branch-name", "*fixed-branch-name"]
