name-template: 'Next release draft'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🎸 Features'
    labels:
      - 'Feature'
      - 'Feat'
  - title: '✨ Enhancements'
    labels:
      - 'Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Fix'
      - 'Bugfix'
      - 'Bug'
  - title: '🧪 Test'
    label: 'Test'
  - title: '✏️ Docs'
    label: 'Docs'
  - title: '💡 Refactor'
    label: 'Refactor'
  - title: '💄 Style'
    label: 'Style'
  - title: '🎡 CI'
    label: 'CI'
  - title: '😎 Developer Experience (DX)'
    label: 'Developer Experience (DX)'
  - title: '⚡️ Performance'
    labels:
      - 'Perf'
      - 'Performance'
  - title: '🤖 Maintenance'
    labels:
      - 'Chore'
      - 'Dependencies'
      - 'depfu'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
references:
  - main
template: |
  ## Release notes

  For more information and the release video check out [the full release page](https://avohq.io/releases/$NEXT_PATCH_VERSION)

  $CHANGES
