name-template: 'Next release draft'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🎸 Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🤖 Maintenance'
    label: 'chore'
  - title: '🧪 Test'
    label: 'test'
  - title: '✏️ Docs'
    label: 'docs'
  - title: '💡 Refactor'
    label: 'refactor'
  - title: '💄 Style'
    label: 'style'
  - title: '🎡 CI'
    label: 'ci'
  - title: '⚡️ Perf'
    label: 'perf'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
references:
  - master
template: |
  ## Release notes

  $CHANGES
