Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false
