fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 3.3.0     # default: RUBY_VERSION
default_ignores: true   # default: true

ignore:                 # default: []
  - 'lib/avo/loaders/fields_loader.rb':
    - Style/MissingRespondToMissing
  - 'spec/requests/avo/authorization/scopes_spec.rb':
    - Lint/ConstantDefinitionInBlock
  - 'lib/**/*':
    - Style/TrailingCommaInHashLiteral
  - 'app/**/*':
    - Style/TrailingCommaInHashLiteral
