default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  port: <%= ENV.fetch('PGPORT', 5433) %>
  username: <%= ENV.fetch('PGUSERNAME', 'postgres') %>
  password: <%= ENV.fetch('PGPASSWORD', nil) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  database: dummy_production
