blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/avo-hq/avo/discussions
    about: Ask questions and discuss with other community members
  - name: Priority Support
    url: https://avohq.io/support
    about: Get fast support from the authors of Avo
