# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/packs
  source_entry_path: entrypoints
  public_root_path: public
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  # use a different sub-folder name
  public_output_path: avo-packs
  webpack_compile_output: true
  extract_css: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  additional_paths_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

# We override the development env. when packed.
# Avo needs to be packed and compiled for when the dev uses it in his development env.
development:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: true

  # Cache manifest.json for performance
  cache_manifest: true

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test
  public_root_path: spec/dummy/public

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
