name: Label PR

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  label-pr:
    permissions:
      contents: read # for TimonVS/pr-labeler-action to read config file
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    uses: avo-hq/support/.github/workflows/label-pr.yml@main
