name: Merge message

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mshick/add-pr-comment@v1
        if: github.event.pull_request.merged == true
        with:
          message: |
            This PR has been merged into `main`. The functionality will be available in the next release.

            Please check [the release guide](https://github.com/avo-hq/avo/blob/main/RELEASE.MD) for more information.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
